name: HardcoreDeathPlugin
version: '${project.version}'
main: us.developers.hardcoredeathplugin.HardcoreDeathPlugin
api-version: '1.20'

commands:
  abandon:
    description: Give up the quests and die forever

  quests:
    description: GUI to manage your quests